### ISSUE TITLE
ollama `llama3.1` and `llama3.2` does not work with API key error

### ISSUE THREAD

**Issue by fujitatomoya** [fujitatomoya/ros2ai#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Regression

This used to work before upgrading ollama.

current version is,

```bash
tomoyafujita@~/DVT/04_DEVENV/ROS2/colcon_ws/src/ros2/ros2ai >ollama --version
ollama version is 0.5.1
```

### Operating System:

Linux tomoyafujita 5.15.0-126-generic #136~20.04.1-Ubuntu SMP Thu Nov 14 16:38:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

rolling (container envirnoment)

### RMW implementation:

rmw_fastrtps_cpp

### Steps to reproduce issue

```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# unset OPENAI_API_KEY
root@tomoyafujita:~/ros2_ws/colcon_ws# export OPENAI_MODEL_NAME=llama3.2
root@tomoyafujita:~/ros2_ws/colcon_ws# export OPENAI_ENDPOINT=http://localhost:11434/v1
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 ai query "what is ROS 2"
Failed to call OpenAI API: Error code: 401 - {'error': {'message': 'Incorrect API key provided: None. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Traceback (most recent call last):
  File "/root/ros2_ws/colcon_ws/install/ros2cli/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli', 'console_scripts', 'ros2')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ros2_ws/colcon_ws/build/ros2cli/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ros2_ws/colcon_ws/build/ros2ai/ros2ai/command/ai.py", line 44, in main
    return extension.main(args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ros2_ws/colcon_ws/build/ros2ai/ros2ai/verb/query.py", line 77, in main
    client.print_result()
  File "/root/ros2_ws/colcon_ws/build/ros2ai/ros2ai/api/openai.py", line 55, in print_result
    for chunk in self.completion_:
TypeError: 'NoneType' object is not iterable
```

### Expected behavior

`ros2ai` should return the answer against the query without any key error.

### Actual behavior

```bash
Failed to call OpenAI API: Error code: 401 - {'error': {'message': 'Incorrect API key provided: None. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
```

**Comment by fujitatomoya** [comment]
looks like validation error for the URL.

```bash
>>> validators.url("http://localhost:11434")
ValidationError(func=url, args={'value': 'http://localhost:11434'})
>>> validators.url("http://127.0.0.1:11434/v1")
True
```
